name       : haskell-alex
version    : 3.2.4
release    : 3
source     :
    - https://hackage.haskell.org/package/alex-3.2.4/alex-3.2.4.tar.gz : d58e4d708b14ff332a8a8edad4fa8989cb6a9f518a7c6834e96281ac5f8ff232
license    : BSD-3-Clause
component  : programming.haskell
summary    : Alex is a tool for generating lexical analysers in Haskell.
description: |
    Alex is a tool for generating lexical analysers in Haskell.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
