name       : haskell-alex
version    : 3.1.7
release    : 2
source     :
    - http://hackage.haskell.org/package/alex-3.1.7/alex-3.1.7.tar.gz : 89a1a13da6ccbeb006488d9574382e891cf7c0567752b330cc8616d748bf28d1
license    : BSD-3-Clause
component  : programming.haskell
summary    : Alex is a tool for generating lexical analysers in Haskell.
description: |
    Alex is a tool for generating lexical analysers in Haskell.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
    - haskell-primitive
    - haskell-QuickCheck
    - haskell-random
    - haskell-tf-random
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
