name       : haskell-alex
version    : 3.2.5
release    : 4
source     :
    - https://hackage.haskell.org/package/alex-3.2.5/alex-3.2.5.tar.gz : b77c8a1270767c64e2adb21a6e91ee7cd904ba17edae17bc20fd03da5256e0e3
license    : BSD-3-Clause
component  : programming.haskell
summary    : Alex is a tool for generating lexical analysers in Haskell.
description: |
    Alex is a tool for generating lexical analysers in Haskell.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
