name       : haskell-alex
version    : 3.1.7
release    : 1
source     :
    - http://hackage.haskell.org/package/alex-3.1.7/alex-3.1.7.tar.gz : 89a1a13da6ccbeb006488d9574382e891cf7c0567752b330cc8616d748bf28d1
license    : BSD-3-Clause
component  : programming
summary    : Alex is a tool for generating lexical analysers in Haskell.
description: |
    Alex is a tool for generating lexical analysers in Haskell.
builddeps  :
    - ghc
    - haskell-primitive
    - haskell-QuickCheck
    - haskell-random
    - haskell-tf-random
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    mv $installdir/usr/share/x86_64-linux-ghc-8.0.1 $installdir/usr/share/ghc-8.0.1